#!/bin/bash
# Quick Reference - MaxMovies Backend Setup

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║        MaxMovies Backend - Quick Reference                     ║"
echo "║         Bearer Auth + Proxy + Video Streaming                  ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""

echo "📋 PROJECT STRUCTURE"
echo "   api/                 - Serverless endpoints"
echo "   ├── homepage.js      - Homepage content"
echo "   ├── info.js          - Movie information"
echo "   ├── search.js        - Search functionality"
echo "   ├── trending.js      - Trending movies"
echo "   ├── sources.js       - Video sources"
echo "   ├── proxy.js         - Video proxy/streaming"
echo "   └── test.js          - Health check"
echo "   utils/               - Shared utilities"
echo "   ├── apiClient.js     - GiftedTech API client (Bearer auth)"
echo "   └── corsHeaders.js   - CORS header utilities"
echo ""

echo "🔑 SETUP CHECKLIST"
echo "   [ ] Get API key from https://movieapi.giftedtech.co.ke"
echo "   [ ] Copy .env.example to .env.local"
echo "   [ ] Add GIFTED_API_KEY to .env.local"
echo "   [ ] Run: npm install"
echo "   [ ] Run: npm run dev"
echo "   [ ] Test: curl http://localhost:3000/api/v2/homepage"
echo ""

echo "🚀 DEPLOYMENT"
echo "   1. Push to GitHub"
echo "   2. Go to https://vercel.com/new"
echo "   3. Import project"
echo "   4. Add environment variable: GIFTED_API_KEY"
echo "   5. Click Deploy"
echo "   6. Test: curl https://YOUR_PROJECT.vercel.app/api/v2/homepage"
echo ""

echo "📡 API ENDPOINTS"
echo "   GET  /api/v2/homepage       - Homepage content"
echo "   GET  /api/v2/trending       - Trending movies"
echo "   GET  /api/v2/search         - Search (?query=...)"
echo "   GET  /api/v2/info           - Movie info (?id=...)"
echo "   GET  /api/v2/sources        - Video sources (?id=...)"
echo "   GET  /api/proxy             - Video proxy (?url=...)"
echo ""

echo "🔐 AUTHENTICATION"
echo "   Header: Authorization: Bearer YOUR_API_KEY"
echo "   Format: gifted_movieapi_378ry3dq7qdlqdgdqg8ordqg78qd0"
echo "   Managed: Via GIFTED_API_KEY environment variable"
echo "   Automatic: apiClient.js adds header to all requests"
echo ""

echo "📚 DOCUMENTATION"
echo "   README.md                  - Full API documentation"
echo "   DEPLOYMENT_GUIDE.md        - Step-by-step deployment"
echo "   API_KEY_MANAGEMENT.md      - API key setup & security"
echo "   .env.example               - Environment variables"
echo ""

echo "🧪 LOCAL TESTING"
echo "   npm run dev                - Start dev server (port 3000)"
echo ""
echo "   # In another terminal:"
echo "   curl http://localhost:3000/api/v2/homepage"
echo ""

echo "✅ ERROR HANDLING"
echo "   401 Unauthorized   - API key is missing or invalid"
echo "   403 Forbidden      - API key authentication failed"
echo "   503 Service Down   - GiftedTech API is down"
echo "   400 Bad Request    - Missing required parameters"
echo "   405 Method Error   - Use GET requests only"
echo ""

echo "🎯 CORS CONFIGURATION"
echo "   Origin: * (all domains allowed)"
echo "   Methods: GET, POST, PUT, DELETE, OPTIONS, PATCH"
echo "   Headers: Content-Type, Authorization, X-Requested-With, etc."
echo ""

echo "🎬 VIDEO PROXY USAGE"
echo "   Endpoint: /api/proxy?url=<video_url>"
echo "   Example: /api/proxy?url=https://example.com/video.mp4"
echo ""
echo "   # In JavaScript:"
echo "   const url = 'https://example.com/video.mp4';"
echo "   const proxyUrl = \`/api/proxy?url=\${encodeURIComponent(url)}\`;"
echo "   video.src = proxyUrl;"
echo ""

echo "🔧 ENVIRONMENT VARIABLES"
echo "   GIFTED_API_KEY    - Your GiftedTech API key (REQUIRED)"
echo ""
echo "   Local (.env.local):"
echo "   GIFTED_API_KEY=gifted_movieapi_378ry3dq7qdlqdgdqg8ordqg78qd0"
echo ""
echo "   Vercel (Settings → Environment Variables):"
echo "   Name: GIFTED_API_KEY"
echo "   Value: Your actual API key"
echo ""

echo "📞 TROUBLESHOOTING"
echo ""
echo "   Problem: Getting 403 Forbidden"
echo "   Solution: Check GIFTED_API_KEY is set in environment variables"
echo ""
echo "   Problem: CORS errors in browser"
echo "   Solution: Use /api/v2/... endpoints, CORS headers are included"
echo ""
echo "   Problem: Video not loading"
echo "   Solution: Use /api/proxy?url=... to stream through server"
echo ""
echo "   Problem: API returns 503"
echo "   Solution: Check if GiftedTech API is down"
echo ""

echo "🔗 USEFUL LINKS"
echo "   GiftedTech API:    https://movieapi.giftedtech.co.ke"
echo "   Vercel Dashboard:  https://vercel.com/dashboard"
echo "   Vercel Docs:       https://vercel.com/docs"
echo "   GitHub Repo:       [Your GitHub URL]"
echo ""

echo "═══════════════════════════════════════════════════════════════"
echo ""
